window.blogPosts = window.blogPosts || [];

window.blogPosts.push({
    title: "Iteration 4: the Beehive",
    date: "April 30, 2026",
    content: `
# Iteration 4: the Beehive
I was not satisfied with the result from the String method so I came up with a more refined method based on hexagonal tiling. I will spare you the details since it's very complicate, but it's also a trade secret. Anyway, the rough idea is we place initial tiles associated with each nation/region. This is also where we assign the metadata to each tile (e.g., the biomes, the nation, etc). Then we do fine-graining (or upscaling or whatever you want to call it) a few times. The new tiles keep the metadata of the previous iteration. Mountain ranges are then placed between some of the national boundaries. Rivers can also be generated by randomly pick the river source near the mountain or inside a forest, then use the [Dijkstra's algorithm](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm) to find the shortest path to the nearest sea. Fun fact, I accidentally re-invented Dijkstra's algorithm while doing this. Roads are similar to the rivers, but it's between two cities.
> [Aug 25, 2024] It's been several months since I last posted about my hobby project--a procedurally generated open-world fantasy game.
> Well, I threw away the previous map generation and made a new one based on hexagonal tiles. In this system, roads and rivers can be generated more beautifully.
> ![ ](images/blog5a.png)

Then I wrote a Python script to generate the cities based on the direction of the exits.
> [Sep 28, 2024] Since I can't draw at the moment (travelling), I got some time for my coding project.
> I wrote a script that generates the detail for each city.
> Love how this turns out. Can't wait to import this into a 3d map in Godot.
> ![ ](images/blog5b.png)

Took a while but finally the cities were implemented on the actual game. Since I initially wrote the city and world generation in Python, it's a hassle to port everything into GDscript, so I precompiled the script into an executable and run it in Godot. I switched the square chunks to hexagonal chunks in this iteration because the tiles are hexagonal. Though I will soon realized that this idea is so stupid.
> [Oct 29, 2024] Making Isekai simulator to escape reality
> (all of these are procedurally generated)
> ![ ](images/blog5c.png)

Next few months I spent my time learning about model rigging. I also finished up some main map features like roads and elevators.
> [Nov 11, 2024] Finally learned how to rig a model!!
> !video[ ](images/blog5d.mp4)
> [Dec 1, 2024] The map is now 90% fully navigable. All cities are connected via a road network. Lifts are connecting the two map levels. (to do: tunnels through the mountains)
> I'm so proud of this result, considering that everything is procedurally generated.
> !video[ ](images/blog5e.mp4)
> [Dec 23, 2024] I started learning game dev about a year ago (it started on Dec 15)
> I love how I rewrote the world generation algorithm like 3 times. The chunk loading is so bad compared to the earlier versions but I have more control over what's going on in my map. Next year is gonna be great.
> ![ ](images/blog5f1.png)
> ![ ](images/blog5f2.png)
> ![ ](images/blog5f3.png)
> ![ ](images/blog5f4.png)
`
});